name: 'AI Code Guard'
description: 'Automatically reviews pull requests using the power of AI'
branding:
  icon: 'git-pull-request'
  color: 'green'

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  openai-api-key:
    description: 'OpenAI API key'
    required: true
  openai-model:
    description: 'OpenAI model to be used for review'
    required: false
    default: 'gpt-3.5-turbo'
  github-api-base-url:
    description: 'The base URL for the GitHub API'
    required: false
    default: 'https://api.github.com'

runs:
  using: 'docker'
  image: 'Dockerfile'